(define (make-account balance password)
  (let ((alert-times 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-cop amount)
        "Call the police")
    (define (alert amount)
      "Incorrect password")
    (define (dispatch pwd m)
      (if (eq? pwd password)
          (begin (set! alert-times 0)
                 (cond 
                  ((eq? m 'withdraw) withdraw)
                  ((eq? m 'deposit) deposit)
                  (else (error "Unknown request: MAKE-ACCOUNT"
                               m))))
          (begin (set! alert-times (1+ alert-times))
                 (if (< alert-times 7)
                     alert
                     call-cop))))
    dispatch))
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'deposit) 100)
((acc 'some-other-password 'withdraw) 200)
