(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (alert amount)
    "Incorrect password")
  (define (dispatch pwd m)
    (cond ((not (eq? pwd password)) alert)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT"
                       m))))
  dispatch)
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'deposit) 100)
((acc 'some-other-password 'withdraw) 200)

