(load "Exer01_22.scm")
(load "Sect01_24_even_odd.scm")
(load "Sect01_26_fermat_test.scm")
(define (search-for-primes a count start-time)
  (cond ((= count 0) (newline)
                      (display "done!"))
        ((fast-prime? a 10) (newline)
                         (display a)
                         (report-prime (- (real-time-clock) start-time))
                         (search-for-primes (next-odd a) (- count 1) (real-time-clock)))
        (else (search-for-primes (next-odd a) count (real-time-clock)))))
(define (next-odd a)
  (if (even? a)
      (+ a 1)
      (+ a 2)))
(define (time-test a)
  (search-for-primes a 3 (real-time-clock)))
