(load "Exer01_43_repeated.scm")
(load "Sect01_17_cube.scm")
(load "Exer01_45_lg2_floor.scm")
(load "Sect01_24_fast_expt.scm")
(load "Sect01_33_fixed_point.scm")
(load "Sect01_34_average_damp.scm")
(define (nth-root x n)
  (fixed-point ((repeated average-damp (lg n))
                (lambda (y) (/ x (fast-expt y (- n 1)))))
               1.0))
