(load "Sect01_17_abs.scm")
(load "Sect01_17_average.scm")
(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2))
       tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (newline)
      (display guess)
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))
(display "without average dampint:")
(fixed-point (lambda (x) (/ (log 1000) (log x)))
             10.0)
(newline)
(newline)
(display "with average dampint:")
(fixed-point (lambda (x) (average x(/ (log 1000) (log x))))
             10.0)
