(load "Sect01_26_fermat_test.scm")
(define (carmichael-test-iter a n)
  (define (try-it a)
    (= (expmod a n n) a))
  (cond ((= a n) true)
    ((try-it a) (carmichael-test-iter (+ a 1) n))
    (else false)))
(define (carmichael-test n)
  (carmichael-test-iter 2 n))  
