(load "Sect01_24_even_odd.scm")
(load "Exer01_41_double.scm")
(load "Exer01_42_compose.scm")
(define (repeated f n)
  (define (repeated-iter result i)
    (cond ((or (= i 1) (< i 1)) result)
          ((even? i) (double (repeated-iter result (/ i 2))))
          (else (compose result (repeated-iter result (- i 1))))))
  (repeated-iter f n))
