(load "Sect01_24_even_odd.scm")
(load "Exer01_31_product.scm")
(define (pi-product a b)
  (define (pi-term x)
    (if (odd? x)
        (/ (+ x 1) (+ x 2))
        (/ (+ x 2) (+ x 1))))
  (define (pi-next x)
    (+ x 1))
  (product pi-term a pi-next b))
