(load "Sect01_17_abs.scm")
(load "Sect01_17_average.scm")
(load "Sect01_17_square.scm")
(define (improve guess x)
    (average guess (/ x guess)))
(define (good-enough? guess x)
    (< (abs (- (square guess) x)) .001))
(define (sqrt-iter guess x)
    (if (good-enough? guess x)
        guess
        (sqrt-iter (improve guess x) x)))
(define (sqrt x)
    (sqrt-iter 1 x))
