(load "Exer02_40.scm")
(define (unique-triple n)
  (accumulate
   append '() (map (lambda (i) (map (lambda (p) (cons i p))
                                    (unique-pair (- i 1))))
                   (enumerate-interval 1 n))))
(define (sum-of-triple t)
  (accumulate + 0 t))
(define (find-triples n s)
  (filter (lambda (t) (or (< (sum-of-triple t) s)
                          (= (sum-of-triple t) s)))
          (unique-triple n)))
