(load "Exer02_68.scm")
(load "Exer02_69.scm")
(define syms1 (list (list 'A 1)
                    (list 'B 2)
                    (list 'C 4)
                    (list 'D 8)
                    (list 'E 16)))
(define tree1 (generate-huffman-tree syms1))
(define syms2 (list (list 'A 1)
                    (list 'B 2)
                    (list 'C 4)
                    (list 'D 8)
                    (list 'E 16)
                    (list 'F 32)
                    (list 'G 64)
                    (list 'H 128)
                    (list 'I 256)
                    (list 'J 512)))
(define tree2 (generate-huffman-tree syms2))
;; tree1
;; (((((leaf a 1)
;;     (leaf b 2) (a b) 3)
;;    (leaf c 4) (a b c) 7)
;;   (leaf d 8) (a b c d) 15)
;;  (leaf e 16) (a b c d e) 31)

;; tree2
;; ((((((((((leaf a 1)
;;          (leaf b 2) (a b) 3)
;;         (leaf c 4) (a b c) 7)
;;        (leaf d 8) (a b c d) 15)
;;       (leaf e 16) (a b c d e) 31)
;;      (leaf f 32) (a b c d e f) 63)
;;     (leaf g 64) (a b c d e f g) 127)
;;    (leaf h 128) (a b c d e f g h) 255)
;;   (leaf i 256) (a b c d e f g h i) 511)
;;  (leaf j 512) (a b c d e f g h i j) 1023)
