(load "Exer02_03_length_of_segment.scm")
(define (make-rectangle l1 w1 l2 w2)
  (cons (cons l1 w1)
        (cons l2 w2)))
(define (selector-width-rectangle r)
  (car (car r)))
(define (selector-length-rectangle r)
  (cdr (car r)))
(define (width-of-rectangle r)
  (length-of-segment (selector-width-rectangle r)))
(define (length-of-rectangle r)
  (length-of-segment (selector-length-rectangle r)))
