(load "Exer02_51_2.scm")
(load "Sect02_24_transform_operations.scm")
(define (split op1 split2)
  (lambda (painter n)
    (if (= n 0)
        painter
        (let ((smaller painter (- n 1)))
          (op1 painter (op2 smaller smaller))))))
(define right-split (split beside below))
(define up-split (split below beside))
