(load "../chap01/Sect01_14_sum_of_squares.scm")
(load "../chap01/Sect01_17_sqrt.scm")
(load "Exer02_02_make_point.scm")
(load "Exer02_02_arithmetic_point.scm")
(load "Exer02_02_make_segment.scm")
(define (length-of-segment l)
  (let ((dif-point (sub-point (start-segment l) (end-segment l))))
    (sqrt (sum-of-squares (x-point dif-point)
                          (y-point dif-point)))))
