(load "Exer02_29_a.scm")
(define (total-weight mobile)
  (+ (branch-weight (left-branch mobile))
     (branch-weight (right-branch mobile))))
(define (branch-weight branch)
  (if (not (mobile? (branch-structure branch)))
      (branch-structure branch)
      (total-weight (branch-structure branch))))
(define (mobile? object)
  (pair? object))
