(load "../chap01/Sect01_17_abs.scm")
(load "../chap01/Sect01_25_gcd.scm")
(define (make-rat n d)
  (define (same-sign? a b)
    (or (and (> a 0) (> b 0))
        (and (< a 0) (< b 0))))
  (let ((g (gcd (abs n) (abs d))))
    (if (same-sign? n d)
        (cons (/ (abs n) g) (/ (abs d) g))
        (cons (- (/ (abs n) g)) (/ (abs d) g)))))
(define (numer x) (car x))
(define (denom x) (cdr x))
