(load "Exer02_62.scm")
(load "Exer02_63.scm")
(load "Exer02_64.scm")
(load "Sect02_33_ordered_sets.scm")
(define (intersection-tree set1 set2)
  (list->tree (intersection-set (tree->list-2 set1)
                                (tree->list-2 set2))))
(define (union-tree set1 set2)
  (list->tree (union-set (tree->list-2 set1)
                         (tree->list-2 set2))))
