(load "Exer02_38.scm")
(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
  (and (variable? v1) (variable? v2) (eq? v1 v2)))
(define (make-sum a1 a2) (list '+ a1 a2))
(define (make-product m1 m2) (list '* m1 m2))
(define (sum? x) (and (pair? x) (eq? (car x) '+)))
(define (addend s) (cadr s))
(define (augend s) (caddr s))
(define (product? x) (and (pair? x) (eq? (car x) '*)))
(define (multiplier p) (cadr p))
(define (multiplicand p) (caddr p))
(define (make-sum . items)
  (let ((sum-list (fold-left make-sum-of-two 0 items)))
    (if (pair? sum-list)
        (cons '+ sum-list)
        sum-list)))
(define (make-sum-of-two a1 a2)
  (cond ((=number? a1 0) a2)
        ((=number? a2 0) a1)
        ((and (number? a1) (number? a2))
         (+ a1 a2))
        ((null? a2) a1)
        ((sum? a1) (append (cdr a1) (list a2)))
        ((product? a1) (append (make-product a1) (list a2)))
        ((pair? a1) (append a1 (list a2)))
        (else (list a1 a2))))
(define (=number? exp num) (and (number? exp) (= exp num)))
(define (make-product . items)
  (fold-right make-product-of-two
              1
              items))
(define (make-product-of-two m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0)) 0)
        ((=number? m1 1) m2)
        ((=number? m2 1) m1)
        ((and (number? m1) (number? m2)) (* m1 m2))
        (else (list '* m1 m2))))
